spring:
  application:
    name: empresa-api

  datasource:
    url: ${DATASOURCE_URL}
    username:  ${DATASOURCE_USERNAME}
    password:  ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: false
    hikari:
      minimum-idle: 20
      maximum-pool-size: 50
      connectionTimeout: 10000
      idleTimeout: 600000
      maxLifetime: 1800000

  flyway:
    enabled=true:
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  server:
    port: 8080
    error:
      include-stacktrace: never


  web:
    error:
      include-stacktrace: never


# Através do hikari eu configuro um pool de conexões abertas para deixa o banco mais resiliente (minimo 20 e maximo 50)